### PR TITLE
feat: Update to support M1 architecture #99

### PR DESCRIPTION
**Pull request by kikiya**
I created this as a draft because I need help testing the changes.

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
At least one pull request committer is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by andreaTP** [comment]
cc. @retgits or @ennru I guess ... I don't have an M1 ...

**Comment by ennru** [comment]
Fixed by now.

**Comment by johanandren** [comment]
I don't think it is, only on the JVM SDK side as far as I know but, I think it is fine to close this and revisit later anyway.

**Pull request closed without merging**
