### PR TITLE
fix: support docker build on arm64 in kalix-scripts

### PR DESCRIPTION
**Pull request by pvlugter**
Refs #99.

Still to be tested on an M1... may be easier to test fully once released, but can be checked locally.

### CODE REVIEW

**Comment by johanandren** [comment]
Tried this out with the js-eventsourced-shopping-cart (noticed the js-customer-registry doesn't use the scripts for some reason), it triggers cross build and the command looks correct:

```
Building docker image with command: docker buildx build --platform=linux/amd64 --tag gcr.io/kalix-public/samples-js-event-sourced-shopping-cart:0.0.2 .
```

But I get this error when the docker build runs `npm ci`, not quite sure I get what the problem is, I tried deleting package.lock.json and re-installing as before triggering, maybe unrelated and happens because of trying to build with unreleased packages?

```
 => ERROR [builder 5/8] RUN npm ci                                                                                                                                             2.3s
------
 > [builder 5/8] RUN npm ci:
#0 2.237 npm ERR! cipm can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.
#0 2.238 npm ERR!
#0 2.239 npm ERR!
#0 2.239 npm ERR! Missing: chai@^4.3.6
#0 2.240 npm ERR! Missing: jsdoc@^3.6.10
#0 2.240 npm ERR! Missing: mocha@^10.0.0
#0 2.240 npm ERR! Missing: uglify-js@^3.16.1
#0 2.240 npm ERR!
#0 2.257
#0 2.257 npm ERR! A complete log of this run can be found in:
#0 2.257 npm ERR!     /root/.npm/_logs/2022-06-23T07_46_37_151Z-debug.log
```

**Review by johanandren — APPROVED** [review]
Marking as approved since the problem is probably something else

**Comment by pvlugter** [comment]
> But I get this error when the docker build runs `npm ci`

Could be from having local snapshot versions in there. Could try a fresh project from the template to confirm this is working.

**Comment by johanandren** [comment]
Tried it out with the -M10 release and a fresh project and everything _almost_ works. The docker image is now successfully built, but:

```
WARNING: No output specified for docker-container driver. Build result will only remain in the build cache. To push result image into registry use --push or to load image into docker use --load
```

And in the next step the image is not available for docker push. I'll look into that and PR.

**Pull request merged**
