### PR TITLE
chore: upgrade Kalix Proxy to 1.0.15

### PR DESCRIPTION
**Pull request by efgpinto**
References [Kalix Proxy 1.0.15](https://github.com/lightbend/kalix-proxy/issues/1605)

### CODE REVIEW

**Comment by efgpinto** [comment]
Leaving this as draft until 1.0.15 is in prd

**Comment by efgpinto** [comment]
CI failing with `is missing the following properties from type 'ProxyInfo__Output': 'internalProxyHostname', 'proxyPort'`..

I believe these are new fields introduced on the protocol and relate with #396 .. So I believe we need to wait for that PR to be merged and then I expect this to be ok.

**Comment by octonato** [comment]
> CI failing with `is missing the following properties from type 'ProxyInfo__Output': 'internalProxyHostname', 'proxyPort'`..
> 
> I believe these are new fields introduced on the protocol and relate with #396 .. So I believe we need to wait for that PR to be merged and then I expect this to be ok.

That's strange. PR #396 should depend on this PR, not the other way around. 

New fields were introduced in proxy 1.0.15, but the SDK should remain compatible.

**Comment by octonato** [comment]
Depends on #401

**Comment by efgpinto** [comment]
Rebased against main. See if CI likes this better :)

**Review by ennru — APPROVED** [review]
LGTM, independent of what CI says.

**Comment by ennru** [comment]
CI is upset about all this.

**Comment by efgpinto** [comment]
> CI is upset about all this.

And rightly so because I forgot @octonato 's contribution to this PR and ended sweeping his changes with the rebase. 😅 
On it :)

**Comment by efgpinto** [comment]
CI happy now.. Merging

**Comment by pvlugter** [comment]
> > CI failing with `is missing the following properties from type 'ProxyInfo__Output': 'internalProxyHostname', 'proxyPort'`..
> > I believe these are new fields introduced on the protocol and relate with #396 .. So I believe we need to wait for that PR to be merged and then I expect this to be ok.
> 
> That's strange. PR #396 should depend on this PR, not the other way around.
> 
> New fields were introduced in proxy 1.0.15, but the SDK should remain compatible.

The `__Output` types are what will be received on the protocol, and these have all properties as required, as they'll have defaults applied for anything that's missing. This test creates the messages directly, so will need values when the protocol is updated. But it's only this test, the rest will be compatible.

**Pull request merged**
